### ISSUE TITLE
unable to use memory_extreme

### ISSUE THREAD

**Issue by egollhofer** [huggingface/local-gemma#24]
When running the sample code with memory_extreme the following error is thrown:

`ValueError: Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit the quantized model. If you want to dispatch the model on the CPU or the disk while keeping these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom `device_map` to `from_pretrained`. Check https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu for more details. 
`

**Comment by gante** [comment]
Hi @egollhofer 👋 

Would you be able to share some information about your hardware, so I may attempt to reproduce (and fix) the issue? 🤗
